/* This file was generated by blade */
extern "C" {
extern const int kSvnInfoCount = 0;
extern const char kSvnInfo[] = "";
extern const char kMainInfo[] = "";
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Fri Dec  7 12:22:39 2018";
extern const char kBuilderName[] = "guozengxin";
extern const char kHostName[] = "n8-125-073";
extern const char kCompiler[] = "GCC 8.2.0";
}
